#!/bin/bash

require_package(){
	apt-get install build-essential libevent-dev libssl-dev libgcrypt11-dev libkrb5-dev libpam0g-dev libwrap0-dev libdb-dev libtdb-dev libmysqlclient-dev avahi-daemon libavahi-client-dev libldap2-dev libcrack2-dev systemtap-sdt-dev libdbus-1-dev libdbus-glib-1-dev libglib2.0-dev tracker libtracker-sparql-1.0-dev libtracker-miner-1.0-dev
}

configure_package(){
	./configure \
	        --with-init-style=debian-systemd \
			--without-libevent \
			--without-tdb \
			--with-cracklib \
			--enable-krbV-uam \
			--with-pam-confdir=/etc/pam.d \
			--with-dbus-sysconf-dir=/etc/dbus-1/system.d \
			--with-tracker-pkgconfig-version=1.0 \
			CFLAGS=-DO_IGNORE
}

install_netatalk(){
	make
	make install
}

_help(){
	echo $"Usage: timeMachine [OPTION] <PATH>
	-r : install package required
	-c [PATH] : get the configure , the path is the source package
	-i [PATH] : install netatalk (make and make install)
	-a [PATH] : install netatalk at one time"
}

if [ $# -eq 2 ]
then
	NETATALK_PATH=$2	
fi

while test $# -gt 0
do
	case "$1" in
		-h | --h | --help)
		_help
		exit 0
		;;
		-r)
		require_package
		exit 1
		;;
		-c)
		cd $NETATALK_PATH
		configure_package
		exit 1
		;;
		-i)
		cd $NETATALK_PATH
		install_netatalk
		exit 1
		;;
		-a)
		require_package
		cd $NETATALK_PATH
		configure_package
		install_netatalk
		exit 1
		;;
		*)
		break	
	esac
done
#require_package

#iconfigure_package
#install_netatalk
