/*
 * common_system.h
 *
 *  Created on: Dec 18, 2015
 *      Author: root
 */

#ifndef HEADER_COMMON_SYSTEM_H_
#define HEADER_COMMON_SYSTEM_H_

/*****Include System Lib*****/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <errno.h>
#include <time.h>
#include <sys/stat.h>
#include <sys/statfs.h>
#include <pwd.h>
#include <sys/mount.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/inotify.h>

#include <sys/time.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <mysql/mysql.h>

#include "./database_operate.h"
#include "./system_operate.h"

#define VARIABLE_NAME				128
#define NORMAL_LENGTH				1024
#define MIDDLE_LENGTH				2048
#define LARGE_LENGTH				4096
#define HUGE_LENGTH					1*128*1024

#define SHELL_VARIABLE_NAME			1024
#define SHELL_CONTENTS				1024
#define SHELL_CONTENTS_MAX			1*128*1024
#define SHELL_CONTENTS_HUGE			10*1024*1024

#define MAXIMUM_NUMBER				10
#define FILES_MAXIMUM_NUMBER		100

enum RESULT_DESCRIPTION
{
	SUCCESS = 100100000,

	/*****Authority Related*****/
	NAME_OR_PASSWORD_ERROR = 100100100,
	USER_EXIST,
	USER_NOT_EXIST,

	CREAT_USER_FAILED,
	DELETE_USER_FAILED,

	CHANGE_PASSWORD_FAILED,
	CHANGE_RIGHTS_FAILED,

	VALID_USER,
	INVALID_USER,
	NO_RIGHTS_USER,

	ACL_ERROR,

	RESET_FAILED,

	/*****File Related*****/
	OPEN_FILE_FAILED = 100100200,
	CLOSE_FILE_FAILED,
	IS_FILE,

	OPEN_DIR_FAILED,
	CLOSE_DIR_FAILED,
	IS_FOLDER,

	CREATE_FILE_FAILED,
	READ_FILE_FAILED,
	WRITE_FILE_FAILED,
	DELETE_FILE_FAILED,
	RENAME_FILE_FAILED, //100100210

	CREATE_FOLDER_FAILED,
	READ_FOLDER_FAILED,
	WRITE_FOLDER_FAILED,
	DELETE_FOLDER_FAILED,
	RENAME_FOLDER_FAILED,

	GET_FILE_STATUS_FAILED,
	FOUND_FILE_FAILED,

	CHANGE_DIR_FAILED,

	UNDEFINED_FILE_TYPE,
	UNDEFINED_OPERATE_FILE_OPTION, //100100220

	INVALID_FILE_NAME,
	INVALID_PATH_NAME,

	COPY_FILE_FAILED,
	COPY_FOLDER_FAILED,

	/*****Shell Related*****/
	EXECUTING_SHELL_FAILED = 100100300,
	CLOSE_SHELL_FAILED,
	SHELL_NO_RETURN,

	/*****Common Related*****/
	PARAMETER_ERROR = 100100400,
	NOT_FOUND,
	FILTER_ERROR,
	DATA_FORMAT_ERROR,
	GIVEN_SPACE_ERROR,
	NOT_EQUAL,
	STRING_TRANSFOR_ERROR,
	STRING_SLICE_ERROR,

	REBOOT_ERROR,
	POWEROFF_ERROR,
	UPDATE_SYSTEM_ERROR,

	SET_LOCAL_TIME_FAILED,

	START_SERVICE_FAILED,
	STOP_SERVICE_FAILED,
	RESTART_SERVICE_FAILED,
	SERVICE_NOT_WORKING,

	/*****Memory Related*****/
	ALLOCATE_MEMORY_FAILED = 100100500,

	/*****MySQL Related*****/
	NO_DEFAULT_PARAMETERS = 100100600,
	NOT_USE_MYSQL,
	CONNECTING_FAILED,
	INVALID_PATH_TYPE,
	FOUND_MORE_DATA,
	WRONG_SQL_FORMAT,
	SQL_QUERY_FAILED,
	GET_PATH_INFOR_FAILED,
	DATA_EXIST,

	/*****cJSON Related*****/
	PARSE_JSON_FAILED = 100100700,
	CREATE_JSON_FAILED,

	/*****Notify Related*****/
	NOTIFY_INIT_ERROR = 100100800,
	READ_NOTIFY_ERROR,

	/*****Samba Related*****/
	SAMBA_FOLDER_EXIST = 100100900,
	SAMBA_FOLDER_NOT_EXIST,

	/*****NTP Related*****/
	GET_NTP_INFOR_FAILED = 100101000,
	SET_NTP_INFOR_FAILED,
	CONNECT_NTP_SERVER_FAILED,
	SELECT_FROM_NTP_FAILED,
	RECEIVE_FROM_NTP_FAILED,
	SEND_NTP_PACKET_FAILED,

	/*****Socket Related*****/
	CREATE_SOCKET_FAILED = 100101100,
	BIND_SOCKET_FAILED,
	GET_HOST_BY_NAME_FAILED,
	IP_ADDRESS_ERROR,

    /*****update Related*****/
	UPDATE_GUIDE_RUNING = 100101200,
	UPDATE_INPUT_EMPTY,
	UPDATE_INPUT_FORMATE_WRONG,
	UPDATE_INPUT_CP_FAILED,
	UPDATE_INPUT_TAR_FAILED,
	UPDATE_INPUT_CHECK_FAILED,
	UPDATE_UPSHELL_NOT_NEED_UPDATE,
	UPDATE_UPSHELL_RESTORE_FAILED,
	UPDATE_UPSHELL_CLEAN_FAILED,
	UPDATE_UPSHELL_DELETE_REBOOTCMD_FAILED,
	UPDATE_UPSHELL_SHELL_FAILED,

	/**********error level*******/
	CRIT_ERROR = 100101300,  //crit error
	ERROR,
	WARNING,
	NOTICE,
	INFO,

	/******client infomation*****/
	INSERT_FAILED = 100101400,
	UPDATE_FAILED,
	GETINFO_FAILED,

	/******minidlna and netatalk infomation*****/
	MINIDLNA_OPEN_FAILED = 100101500,
	NETATALK_OPEN_FAILED,
	NETATALK_NOT_EXIST,

	/*****Undefined*****/
	UNDEFINED_ERROR = 100200000,
};


#endif /* HEADER_COMMON_SYSTEM_H_ */
